name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Lint test
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Prepare output dir
        run: |
          mkdir -p output
          cp -R .next public package.json next.config.js output/

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/

  deploy:
    name: Deploy to personal repository
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Download output artifact
        uses: actions/download-artifact@v4
        with:
          name: output
          path: output/

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FE_GITHUB_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: seonysun
          destination-repository-name: localstory-FE
          user-email: ${{ secrets.FE_ACCOUNT_EMAIL }}
          commit-message: 'Deploy from GitHub Actions'
          target-branch: develop

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
